namespace Syhler.InformationGathering.Application.Services.YoutubeApi.Enum
{
    public enum YoutubeCategory
    {
        AutoVehicles = 2,
        FilmAndAnimation = 1,
        Music = 10,
        PetsAndAnimals = 15,
        Sports = 17,
        ShortMovies = 18,
        TravelAndEvents = 19,
        Gaming = 20,
        Videoblogging = 21,
        PeopleAndBlogs = 22,
        Comedy = 23,
        Entertainment = 24,
        NewsAndPolitics = 25,
        HowtoAndStyle = 26,
        Education = 27,
        ScienceAndTechnology = 28,
        NonprofitsAndActivism = 29,
        Movies = 30,
        AnimeAndAnimation = 31,
        ActionAndAdventure = 32,
        Classics = 33,
        Comedy2 = 34,
        Documentary = 35,
        Drama = 36,
        Family = 37,
        Foreign = 38,
        Horror = 39,
        SciFiAndFantasy =40,
        Thriller = 41,
        Shorts = 42,
        Shows = 43,
        Trailers = 44,
    }
}